spring.application.name=Distributed-Rate-Limiter
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.endpoints.web.exposure.include=*

rate-limiter:
    capcaity: 10
    refill-rate: 5
